// Event actions

export const LOAD_EVENTS_LIST_SUCCESS = 'LOAD_EVENTS_LIST_SUCCESS';

export const LOAD_EVENTS_LIST_FAILURE = 'LOAD_EVENTS_LIST_FAILURE';

export const LOAD_SINGLE_EVENT_SUCCESS = 'LOAD_SINGLE_EVENT_SUCCESS';

export const LOAD_SINGLE_EVENT_FAILURE = 'LOAD_SINGLE_EVENT_FAILURE';
