const topics = [
  // '.NET',
  // 'AADL',
  // 'Activity',
  // 'ADAM',
  // 'Add-ins',
  // 'Adobe',
  // 'ADOBE CQ + HYBRIS',
  // 'Advanced analytics',
  // 'Advanced Technology',
  // 'AEM',
  // 'Age of BI',
  // 'Agile',
  // 'Agile Tester',
  // 'Agile workshop',
  // 'Agility',
  'AJAX',
  // 'Algorithms',
  // 'Amazon',
  // 'Americanism',
  // 'Analytics',
  // 'Android',
  'Angular 2',
  'Angular2',
  'AngularJS',
  // 'Ansible',
  // 'Anti-fragility',
  // 'Antlr',
  // 'Apache Cordova',
  // 'Apache Mesos',
  // 'API',
  // 'Application',
  // 'AR',
  // 'Architecture',
  // 'Artificial Intelligence',
  // 'Assessment',
  // 'Asset management',
  // 'Augmented reality',
  // 'Aurelia',
  // 'Automation',
  // 'AUTOSAR',
  // 'AWD (Adaptive Web Design)',
  // 'AWS',
  // 'Azure',
  'BackboneJS',
  // 'Backend Development',
  // 'Batch',
  // 'BDD',
  // 'Best Practices',
  // 'BI',
  // 'Big Data',
  // 'Big data platform',
  // 'BIGGEST CUSTOMER IMPACT',
  // 'Binary',
  // 'Blockchain',
  // 'Booking',
  'Bootstrap',
  // 'Building blocks',
  // 'Business',
  // 'Business Analysis',
  // 'Business Intelligence',
  // 'Business strategy',
  // 'Buying',
  // 'C',
  // 'C#',
  // 'C++',
  // 'Cache',
  // 'Campaigns',
  // 'Carrier',
  // 'Certification',
  // 'Challenge',
  // 'Chef',
  // 'Children',
  // 'Chrome',
  // 'Chrome App',
  // 'ChromeCast',
  // 'CI',
  // 'Client Speaking',
  // 'Closing',
  // 'Cloud',
  // 'Cloud Management',
  // 'CMS',
  // 'CoAP',
  // 'Code',
  // 'Code Coverage',
  // 'Code Quality',
  // 'Code Review',
  // 'code smells',
  'CoffeeScript',
  // 'Collaboration',
  // 'Commerce',
  // 'Communications',
  // 'Community',
  // 'Competency Centers',
  // 'Composition',
  // 'Compression',
  // 'Computer vision',
  // 'Concurrency',
  // 'Consulting',
  // 'Consumer market',
  // 'Containers',
  // 'Content management',
  // 'Continuous Delivery',
  // 'Continuous deployment (ETL)',
  // 'Core Processes',
  // 'Creativity',
  // 'Cross-platform',
  'CSS',
  'Css Animations',
  // 'css-modules',
  // 'CSSO',
  // 'Cucumber',
  // 'Culture',
  // 'Curriculum',
  // 'Customer success',
  // 'Cutting edge tech',
  // 'Data driven',
  // 'Data flow',
  // 'Data Integration',
  // 'Data preparation',
  // 'Data processing',
  // 'Data Science',
  // 'Data Structures',
  // 'Data Warehousing',
  // 'Databases',
  // 'debugging',
  // 'Deliver',
  // 'Delivering value',
  // 'Delivery',
  // 'Delivery management',
  // 'Dep',
  // 'Deployment',
  // 'Design',
  // 'Dev environment',
  // 'Development',
  // 'DevNext',
  // 'Devops',
  // 'DevOps &amp; Automation',
  // 'DICOM',
  // 'Digital',
  // 'Digital Engagement',
  // 'Digital Lab',
  // 'Digital platforms',
  // 'Discover',
  // 'Disrupt',
  // 'Docker',
  // 'Dojo',
  'DOM',
  // 'Doses',
  // 'DSL',
  // 'e-kids',
  // 'E2E Testing',
  // 'Earnings results',
  // 'Easyb',
  'ECMAScript6',
  // 'Ecommerce',
  // 'Ecommerce platform',
  // 'Ecosystem',
  // 'Education',
  // 'Educator',
  // 'Elastic Container Service (ECS)',
  // 'Electron',
  // 'ELK',
  // 'Empathy',
  // 'Empowerment',
  // 'Engineering',
  // 'Engprod',
  // 'EngX',
  // 'Enterprise Content Management',
  // 'Enterprise Marketing Software Suites',
  // 'EPAM',
  // 'EPAM DIGITAL PLATFORM',
  // 'EPAM Offering',
  // 'Esp',
  // 'Estimation Techniques',
  // 'Etl',
  // 'Excellence',
  // 'Execution',
  // 'Experience management',
  // 'EXPERTISE THAT SHAPES THE FUTURE OF DIGITAL WORLD',
  // 'Fast data',
  // 'Finance and Banking',
  // 'Financial services',
  // 'FinNext',
  // 'FitNesse',
  // 'FIX',
  // 'Flux',
  'Front-end development',
  'Frontend Development',
  // 'FRP (Functional Reactive Programming)',
  // 'Full Stack Development',
  // 'Fun',
  // 'Functional Programming',
  // 'Functional Testing',
  // 'Functor',
  // 'Fundamentals',
  // 'Game',
  // 'Game Development',
  // 'GameDevelopment',
  // 'Gaps and solutions',
  // 'Git',
  // 'GitHub',
  // 'Global',
  // 'Google',
  // 'Grammatics',
  // 'GRAND PRIX – CEO SHOWCASE AWARD',
  // 'Grow',
  // 'Growth',
  'Grunt',
  // 'Hackathon',
  // 'Healthcare',
  // 'High Performance',
  // 'Highload',
  // 'History',
  // 'HoloLens',
  // 'HR Summit',
  'HTML',
  'HTML5',
  // 'HTTP',
  // 'HTTP2',
  // 'Hybrid',
  // 'Hybrid Mobile Development',
  // 'Hybris',
  // 'IBM',
  // 'Ignite',
  'Immutable',
  'ImmutableJS',
  // 'Information architecture',
  // 'Infrastructure Management',
  // 'Innovation',
  // 'Innovation Program',
  // 'Insights',
  // 'Insurance',
  // 'Intercepting',
  // 'Internal customer',
  // 'Internal trainings',
  // 'Internationalization',
  // 'Internet of things',
  // 'Interview',
  // 'Introduction',
  // 'iOS',
  // 'IoT',
  // 'Isomorphic JavaScript',
  // 'Java',
  'JavaScript',
  'JavaScript Frameworks',
  'JavaScript Patterns',
  'JavaScript Testing',
  // 'Java|DevOps',
  // 'Jbehave',
  // 'Jenkins',
  // 'Jira',
  'jQuery',
  'JS Core',
  // 'JSoutOfBrowser',
  // 'Junit',
  // 'Karma',
  // 'KDD',
  // 'Keynote',
  // 'Kids',
  // 'Kinesis',
  // 'Kotlin',
  // 'Kubernetes',
  // 'LambdaCD',
  // 'Language',
  // 'Leadership',
  // 'Learn',
  // 'Legacy systems',
  // 'Liberty Global',
  // 'Life Sciences',
  // 'Lightning talk',
  // 'Live coding',
  // 'Local',
  // 'Logstash',
  // 'Lost in translation',
  // 'LTR-RTL',
  // 'LWM2M',
  // 'Machine Learning',
  // 'Madness',
  // 'MainStage',
  // 'Making it real',
  // 'Management',
  // 'Manager',
  // 'Market',
  // 'Media &amp; Entertainment',
  // 'memory leaks',
  // 'Mental &amp; Physical Health',
  // 'Messaging',
  // 'MeteorJS',
  // 'methodology',
  // 'Metrics',
  // 'Microservice',
  // 'Microsoft',
  // 'Minifier optimization',
  // 'Mobile',
  // 'Mobile platforms',
  // 'Mobile Testing',
  // 'Monad',
  // 'MongoDB',
  // 'MOST ADVANCED TECHNOLOGY PROJECT',
  // 'MOST IMPACTFUL DATA PROJECT',
  // 'MOST TRANSFORMATIVE SOLUTION',
  // 'Motivation',
  // 'Moving',
  // 'MPEG-DASH',
  // 'MQTT',
  // 'MVC',
  // 'MVVM',
  // 'Native',
  // 'Netflix OSS',
  // 'Network Performance',
  // 'Neural networks',
  // 'New role',
  // 'Ngrx',
  'NodeJS',
  // 'NoSQL',
  'NPM',
  // 'Office 365',
  // 'Office365',
  // 'Omnichannel',
  // 'On-line Booking',
  // 'Open IMA',
  // 'Open Source',
  // 'Opening Ceremony',
  // 'Openstack',
  // 'Optimization',
  // 'Other',
  // 'Overview',
  // 'PaaS',
  // 'Payment Cards',
  // 'People',
  // 'people 1',
  // 'people 2',
  // 'people 3',
  // 'people 4',
  // 'people 5',
  // 'Perception',
  // 'Personal development plan',
  // 'Personal efficiency',
  // 'Personalisation',
  // 'PHP',
  // 'Physical to digital',
  // 'Plan',
  // 'Plenary Session',
  // 'PM',
  // 'Polymorphism',
  // 'Presales',
  // 'Processes',
  // 'Product',
  // 'Products',
  // 'Programmer',
  // 'Programming',
  // 'Project Planning',
  'Promises',
  // 'Proposals',
  // 'Protractor',
  // 'Psychology',
  // 'Public speaking',
  // 'Purpose',
  // 'Push Notifications',
  // 'Q&amp;A session',
  // 'QA',
  // 'Quality',
  // 'Radiology',
  'React',
  'React Fiber',
  'React Next',
  'Reactive programming',
  'ReactJS',
  // 'Recognition',
  'Redux',
  // 'Refactoring',
  // 'Reporting',
  // 'Requirements',
  // 'Research',
  // 'Reservation',
  'REST',
  // 'Retail',
  // 'Review',
  // 'Ruby',
  // 'RUP',
  // 'RWD (Responsive Web Design)',
  // 'RX',
  'RxJS',
  // 'Sale',
  // 'SAP',
  // 'Saxon',
  // 'Scene7',
  // 'School',
  // 'Scratch',
  // 'Scrum',
  // 'Search',
  // 'SEC Online',
  // 'Security',
  // 'Selenium',
  // 'Self-development',
  // 'Selling',
  // 'Service design',
  // 'Service Worker',
  // 'Setup',
  // 'SharePoint',
  // 'SharePoint 2016',
  // 'Showcase',
  // 'SiteCatalyst',
  // 'SiteCore',
  // 'Skills',
  // 'SOA',
  // 'SOCIAL IMPACT PROJECT',
  // 'Social Responsibility',
  // 'Software Development',
  // 'Software Testing',
  // 'Solutioning',
  // 'Solutions',
  // 'SPA (Single Page Applications)',
  // 'Specflow',
  // 'Speech',
  // 'Spinners',
  // 'Spring',
  // 'Spring Boot',
  // 'Startup',
  // 'Strategy',
  // 'Students',
  // 'Success',
  // 'Synthesis',
  // 'T-shaped tester',
  // 'TAF',
  // 'TDD (Test-driven Development)',
  // 'Teacher',
  // 'Team efficiency',
  // 'Technology',
  // 'Test &amp; Target',
  // 'Testing',
  // 'TestNG',
  // 'Time',
  // 'Tips And Tricks',
  // 'Travel',
  // 'Travelsolutions',
  // 'Trends',
  // 'TV',
  // 'TV everywhere',
  'TypeScript',
  'UDX',
  'UI',
  // 'Useful Tools',
  // 'User experience',
  // 'Userjourney',
  // 'UWP',
  // 'UX',
  // 'UX Design',
  // 'Vagrant',
  // 'Vault',
  // 'VideoStreaming',
  // 'Virtualization',
  // 'Vision',
  'vue.js',
  // 'vuex',
  // 'W3C',
  // 'WASM',
  // 'Waterfall',
  // 'WaveNext',
  // 'Web',
  // 'Web Assembly',
  // 'Web Audio API',
  // 'Web Development',
  // 'Web MIDI API',
  // 'Web Performance Optimization',
  // 'Web Security',
  // 'Web Services',
  // 'Web Technologies',
  // 'Web Workers',
  // 'Webdriver',
  // 'WebGL',
  // 'webpack',
  // 'WebRTC',
  // 'WebSockets',
  // 'WebVR (Web Virtual Reality)',
  // 'Windows 10',
  // 'Work-Life Balance',
  // 'Workshop',
  // 'Xamarin',
  // 'XAML',
  // 'Xen Automotive',
  // 'XML',
  // 'XSLT',
  // 'XSS',
  // 'С++',
];
export { topics };
